#!/bin/bash
# Creates Config/Signing.local.xcconfig from the Apple Development identity in
# the keychain.
#
# Without a stable signature macOS re-asks for every permission on each rebuild,
# because TCC keys grants to the signing team, not to the bundle path.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
config="$repo_root/Config/Signing.local.xcconfig"

if [[ -f "$config" ]]; then
	echo "signing: Config/Signing.local.xcconfig already exists, leaving it alone"
	exit 0
fi

# The team id is the certificate's OU. The value in parentheses in the identity
# name ("Apple Development: Name (XXXXXXXXXX)") is the user id and signing with
# it fails with a misleading "no Mac Development certificate found".
team="$(security find-certificate -c "Apple Development" -p 2>/dev/null |
	openssl x509 -noout -subject 2>/dev/null |
	sed -n 's/.*OU *= *\([A-Z0-9]*\).*/\1/p' |
	head -1)"

if [[ -z "$team" ]]; then
	echo "signing: no Apple Development identity found, keeping ad-hoc signing"
	echo "signing: permissions will reset on every rebuild"
	exit 0
fi

cat >"$config" <<EOF
// Generated by scripts/setup-signing.sh — gitignored.
SIDEKICK_CODE_SIGN_STYLE = Manual
SIDEKICK_CODE_SIGN_IDENTITY = Apple Development
SIDEKICK_DEVELOPMENT_TEAM = $team
EOF

echo "signing: using the Apple Development identity of team $team"
