#!/bin/bash
# Writes Config/Version.xcconfig from git so CURRENT_PROJECT_VERSION grows
# monotonically — Sparkle compares that number, not the marketing string.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
output="$repo_root/Config/Version.xcconfig"

if git -C "$repo_root" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
	tag="$(git -C "$repo_root" describe --tags --abbrev=0 2>/dev/null || true)"
	marketing="${tag#v}"
	if [[ -z "$marketing" ]]; then
		marketing="0.1.0"
	fi
	build="$(git -C "$repo_root" rev-list --count HEAD)"
else
	marketing="0.1.0"
	build="1"
fi

cat >"$output" <<EOF
// Generated by scripts/version.sh — do not edit.
MARKETING_VERSION = $marketing
CURRENT_PROJECT_VERSION = $build
EOF
